# Generated by Django 5.2.5 on 2025-08-29 11:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(help_text='A short summary or excerpt of the post.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date the post was published.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='read_more_url',
            field=models.URLField(help_text='The URL to the full blog post.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='The title of the blog post.', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='A brief description of the project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_repo_url',
            field=models.URLField(blank=True, help_text='Optional URL for the GitHub repository.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='An image to represent the project.', upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_demo_url',
            field=models.URLField(blank=True, help_text='Optional URL for a live demo.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text="List the technologies used (e.g., 'Django, React, PostgreSQL').", max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='The title of the project.', max_length=200),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(help_text="The category of the skill (e.g., 'Backend', 'Frontend').", max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text="The name of the skill (e.g., 'Python', 'Django').", max_length=50),
        ),
    ]
