# Generated by Django 5.2.5 on 2025-08-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_delete_blog_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='An image to represent the project.', null=True, upload_to='project_images/'),
        ),
    ]
